# Generated by Django 2.2.6 on 2019-10-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='drafted',
            field=models.BooleanField(default=False),
        ),
    ]
