# Generated by Django 2.2.6 on 2019-10-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
